<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.euphyllia.skyllia</groupId>
        <artifactId>skyllia-addons</artifactId>
        <version>${revision}</version>
    </parent>

    <groupId>fr.euphyllia.skylliaore</groupId>
    <artifactId>SkylliaOre</artifactId>
    <packaging>jar</packaging>

    <name>Skyllia Addon - Ore</name>

    <repositories>
        <repository>
            <id>oraxen</id>
            <url>https://repo.oraxen.com/releases</url>
        </repository>
        <repository>
            <id>nexomc</id>
            <url>https://repo.nexomc.com/releases</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.21.3-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.th0rgal</groupId>
            <artifactId>oraxen</artifactId>
            <version>1.180.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.nexomc</groupId>
            <artifactId>nexo</artifactId>
            <version>1.16.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>fr.euphyllia.skyllia</groupId>
            <artifactId>skyllia-database</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>fr.euphyllia.skyllia</groupId>
            <artifactId>skyllia-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>fr.euphyllia.skyllia</groupId>
            <artifactId>skyllia-plugin</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
